In [1]:
import numpy as np
import pandas as pd
traffic=pd.read_excel('04월 서울시 교통량 조사자료.xlsx')
traffic_latlon=pd.read_excel('04월 서울시 교통량 조사자료-수집지점 좌표.xlsx')
charger=pd.read_excel('전기차 충전소 설치현황_20210522.xls')

In [30]:
distance_score

array([[111.60645143, 110.80162454, 110.        , ..., 136.20939762,
        137.00364959, 137.80058055],
       [111.01801656, 110.20889256, 109.40292501, ..., 135.60235986,
        136.40014663, 137.20058309],
       [110.43550154, 109.62207807, 108.81176407, ..., 135.        ,
        135.80132547, 136.60527076],
       ...,
       [154.18495387, 153.6814888 , 153.18289722, ..., 168.76018488,
        169.2837854 , 169.81166038],
       [155.04837955, 154.54772726, 154.05193929, ..., 169.61426827,
        170.13524032, 170.66048166],
       [155.91343752, 155.41557194, 154.9225613 , ..., 170.4699387 ,
        170.98830369, 171.5109326 ]])

In [31]:
np.save('distance_score_500x300', distance_score)

In [33]:
print('평균 :', np.mean(distance_score))
print('표준편차 :', np.std(distance_score))

평균 : 38.28660504675492
표준편차 : 35.46599326959018


In [37]:
# 더 큰 단위에서 최대값 구하기
def max_larger(score):
    max_larger_score = np.zeros((31, 54))
    for i in range(31):
        for j in range(54):
            try:
                max_larger_score[i, j] = np.max(score[10*i:10*(i+1), 10*j:10*(j+1)])
            except:
                max_larger_score[i, j] = np.max(score[10*i:, 10*j:])
    return max_larger_score

In [103]:
# n개의 가장 큰 점수 구하기
def n_largest_scores(score, n):
    n_largest_score = np.zeros(n)
    score_ = score.ravel()
    score_.sort()
    return score_[-n:]

In [38]:
max_larger_distance_score = max_larger(distance_score)

In [39]:
max_larger_distance_score

array([[111.60645143, 103.7111373 ,  96.20810777, ..., 126.15070353,
        133.84319183, 137.80058055],
       [106.        ,  97.65244493,  89.64373932, ..., 119.80818002,
        127.88275881, 132.01893804],
       [101.07423015,  92.28217596,  83.76156637, ..., 113.99122773,
        122.44998979, 126.76355943],
       ...,
       [145.64683313, 140.54536634, 135.98897014, ..., 153.56106277,
        158.685223  , 161.41871019],
       [154.18495387, 149.37536611, 145.0965196 , ..., 162.36070953,
        167.21542991, 169.81166038],
       [155.91343752, 151.15885684, 146.93195704, ..., 163.68567439,
        168.94081804, 171.5109326 ]])

In [41]:
max_larger_distance_score.shape

(31, 54)

In [107]:
ten_largest_scores = n_largest_scores(max_larger_distance_score, 10)

In [108]:
ten_largest_scores

array([154.76756766, 155.91343752, 158.685223  , 161.41871019,
       162.36070953, 163.68567439, 167.21542991, 168.94081804,
       169.81166038, 171.5109326 ])

In [110]:
for i in ten_largest_scores:
    print(np.where(distance_score == i))

(array([283, 292, 301], dtype=int64), array([531, 516, 509], dtype=int64))
(array([290, 301], dtype=int64), array([522,   0], dtype=int64))
(array([289], dtype=int64), array([529], dtype=int64))
(array([289], dtype=int64), array([534], dtype=int64))
(array([299], dtype=int64), array([519], dtype=int64))
(array([301], dtype=int64), array([519], dtype=int64))
(array([299], dtype=int64), array([529], dtype=int64))
(array([301], dtype=int64), array([529], dtype=int64))
(array([299], dtype=int64), array([534], dtype=int64))
(array([301], dtype=int64), array([534], dtype=int64))
